name: notion_connect
description: "API Client Package for Notion API"
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  logger: ^2.5.0
  retrofit: ^4.6.0

dev_dependencies:
  build_runner: ^2.6.0
  custom_lint: ^0.7.5
  flutter_test:
    sdk: flutter
  freezed: ^3.2.0
  freezed_lint: ^0.0.9
  json_serializable: ^6.10.0
  retrofit_generator: ^10.0.0

