name: notion_connect
description: "API Client Package for Notion API"
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  logger: ^2.5.0
  retrofit: ^4.4.2

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  flutter_test:
    sdk: flutter
  freezed: ^3.0.4
  freezed_lint: ^0.0.9
  json_serializable: ^6.9.4
  retrofit_generator: ^9.1.9

