name: Flutter CI
on:
  push:
    branches:
      - main  # mainブランチへのpush時に実行
  pull_request:
    branches:
      - main  # mainブランチへのPR作成時に実行
  workflow_dispatch:

jobs:
  test:
    name: Run CI
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.NOTION_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.32.7'
          cache: false
      - name: Check Flutter Version
        run: flutter --version
      - name: Clean Flutter build
        run: flutter clean
      - name: Install dependencies
        run: flutter pub get
      - name: Run linter
        run: flutter analyze
      - name: Run tests
        run: flutter test --dart-define=API_KEY=$API_KEY
